name: CD Pipeline

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Set up KinD
        uses: helm/kind-action@v1.8.0
        with:
          version: v0.22.0
          cluster_name: kind

      - name: Log in to GHCR
        run: echo "${{ github.token }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Pull image from GHCR
        run: |
          OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          IMAGE=ghcr.io/$OWNER/myapp:latest
          docker pull $IMAGE

      - name: Load Docker image to Kind
        run: |
          OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          IMAGE=ghcr.io/$OWNER/myapp:latest
          kind load docker-image $IMAGE --name kind

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.7.0

      - name: Terraform Init & Apply
        run: |
          terraform -chdir=terraform init
          terraform -chdir=terraform apply -auto-approve
